accounts/urls.py
from django.urls import path
from .views import Signup
from django.contrib.auth import views as auth_views

app_name='accounts'

urlpatterns = [
    path('signup/', Signup, name='signupview'),
    path('signin/', auth_views.LoginView.as_view(template_name='accounts/signin.html'), name='signinview'),
    path('logout/', auth_views.LogoutView.as_view(template_name='accounts/logout.html'), name='logoutview'),
]

home/urls.py
from django.urls import path
from .views import home, records, details, book_room

app_name = 'home'

urlpatterns = [
    path('', home, name='homeview'),
    path('details/<int:ID>/', details, name='detailview'),
    path('records/', records, name='recordview'),
    path('book_room/', book_room, name='bookroomview')
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('home.urls')),
    path('accounts/', include('accounts.urls')),
]

accounts/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Hotel_Room_Application_Record(models.Model):
    #Room number is alphanumeric
    Room_number = models.CharField(max_length=5)
    Amount_paid_in_Naira = models.DecimalField(max_digits=10000000, decimal_places=2)
    Occupant_Name = models.CharField(max_length=1000)
    Occupant_email = models.EmailField()
    Occupant_occupation = models.CharField(max_length=10000)
    Number_of_night = models.IntegerField()
    Start_date = models.DateField()
    End_date = models.DateField()
    Registered_by = models.ForeignKey(User, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.Occupant_Name + " - " + self.Room_number

    #def snippet(self):
    #   return self.Occupant_Name[:1] + "..."

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm

# Create your views here.
def Signup(request):
    if request.method == 'POST':
        user_data = UserCreationForm(request.POST)
        if user_data.is_valid:
            user_data.save()
            return redirect("accounts:signinview")
        else:
            return redirect("accounts:signnupview")
    context = {
        'form': UserCreationForm
    }
    return render(request, 'accounts/signup.html', context)

home/views.py
from django.shortcuts import render, redirect
from .models import Hotel_Room_Application_Record

# Create your views here.
def home(request):
    return render(request, 'home/index.html')

def records(request):
    posts = Hotel_Room_Application_Record.objects.all().order_by('-timestamp')
    context = {
        'posts': posts
    }
    return render(request, 'home/booking_records.html', context)

def details(request, ID):
    detail = Hotel_Room_Application_Record.objects.get(id=ID)
    context = {
        'posts':detail
    }
    return render(request, 'home/details.html', context )

def book_room(request):
    if request.method == 'POST':
        roomnumber = request.POST.get('Roomnumber')
        amountpaid = request.POST.get('Amountpaid')
        occupantname = request.POST.get('Occupantname')
        occupantemail = request.POST.get('Occupantemail')
        occupantoccupation = request.POST.get('Occupantoccupation')
        nightNumber = request.POST.get('NightNumber')
        startdate = request.POST.get('Startdate')
        enddate = request.POST.get('Enddate')
        admin_user = request.user

        new_records = Hotel_Room_Application_Record(Room_number=roomnumber, Amount_paid_in_Naira=amountpaid, Occupant_Name=occupantname, Occupant_email=occupantemail, Occupant_occupation=occupantoccupation, Number_of_night=nightNumber, Start_date=startdate, End_date=enddate, Registered_by=admin_user)

        new_records.save()
        return redirect('home:recordview')
    return render(request, 'home/book_room.html')

accounts/templates/accounts/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <header>
        <center><h1>XYZ HOTEL</h1></center>
    </header>
    <main>
        <p>You are logged out</p>
        <a href="{% url 'home:bookroomview' %}"><button>Sign in back</button></a>
        <p>or</p>
        <p><a href="{% url 'accounts:signupview' %}">Register</a></p>
    </main>
    <footer>

    </footer>
</body>
</html>

accounts/templates/accounts/signin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <header>
        <center><h1>XYZ HOTEL</h1></center>
    </header>
    <main>
        <p><b>Login Here</b></p>
        <form method="post">
            {% csrf_token %}
            <div>{{ form.as_p }}</div>
            <input type="submit" value="SignIn">
        </form>
        <div>Don't have an account? <span><a href="{% url 'accounts:signupview' %}">Sign Up</a></span></div>
    </main>
    <footer>

    </footer>
</body>
</html>

accounts/templates/accounts/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <header>
        <center><h1>XYZ HOTEL</h1></center>
    </header>
    <main>
        <p><b>Make sure your password is as stong as possible please</b></p>
        <form method="post">
            {% csrf_token %}
            <div>{{ form.as_p }}</div>
            <input type="submit" value="Signup">
        </form>
        <div>Already have an account? <span><a href="{% url 'accounts:signinview' %}">Sign In</a></span></div>
    </main>
    <footer>

    </footer>
</body>
</html>

home/templates/home/book_room.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Hotel Booking Records</title>
        <style>
            body {
                margin-left:100px;
                margin-right:100px;
                margin-bottom:100px;
            }
            main{
                margin-top: 40px;
            }
        </style>
    </head>
    <body>
        <header>
            <center>
                <h1>XYZ HOTEL</h1>
                <div>
                    <a href="{% url 'home:recordview' %}"><button>Check Existing Records</button></a>
                    <a href="{% url 'accounts:logoutview' %}"><button>Log Out</button></a>
                </div>
            </center>
        </header>
        <main>
            <center><h2>Book Hotel Room</h2></center>
            <form action="{% url 'home:bookroomview' %}" method="post">
                {% csrf_token %}
                <div>
                    <label for="Roomnumber">Room number</label><br>
                    <input type="text" name="Roomnumber" id="Roomnumber">
                </div>
                <div>
                    <label for="Amountpaid">Amount Paid in Naira</label><br>
                    <input type="number" name="Amountpaid" id="Amountpaid">
                </div>
                <div>
                    <label for="Occupantname">Occupant name</label><br>
                    <input type="text" name="Occupantname" id="Occupantname">
                </div>
                <div>
                    <label for="Occupantemail">Occupant Email</label><br>
                    <input type="email" name="Occupantemail" id="Occupantemail">
                </div>
                <div>
                    <label for="Occupantoccupation">Occupant Occupation</label><br>
                    <input type="text" name="Occupantoccupation" id="Occupantoccupation">
                </div>
                <div>
                    <label for="NightNumber">Number of night</label><br>
                    <input type="number" name="NightNumber" id="NightNumber">
                </div>
                <div>
                    <label for="Startdate">Start Date</label><br>
                    <input type="date" name="Startdate" id="Startdate">
                </div>
                <div>
                    <label for="Enddate">End Date</label><br>
                    <input type="date" name="Enddate" id="Enddate">
                </div>
                <div>
                    <input type="submit" value="Book Room" id="submit">
                </div>
            </form>
        </main>
        <footer></footer>
    </body>
</html>

home/templates/home/booking_records.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        body {
            margin-left:100px;
            margin-right:100px;
            margin-bottom:100px;
        }
        main{
            margin-top: 40px;
        }
        div {
            border: 1px solid #000000;
            border-radius: 8px;
            float: left;
            margin-right: 20px;
            margin-top: 20px;
            color: #000000;
        }
    </style>
</head>
<body>
    <header>
        <center>
            <h1>XYZ HOTEL</h1>
            <div>
                <a href="{% url 'home:bookroomview' %}"><button>Book a room</button></a>
                <a href="{% url 'accounts:logoutview' %}"><button>Log Out</button></a>
            </div>
        </center>
    </header>
    <main>
        <center><h2>Hotel Booking Records</h2></center>
        {% for Hotel_Room_Application_Record in posts  %}
        <a href="{% url 'home:detailview' Hotel_Room_Application_Record.id %}">
            <div>
                <h1>Name: <span> {{ Hotel_Room_Application_Record.Occupant_Name }} </span></h1>
                <h1>Occupation: <span> {{Hotel_Room_Application_Record.Occupant_occupation }} </span></h1>
                <h1>Room Number: <span> {{Hotel_Room_Application_Record.Room_number}} </span></h1>
                <h1>Time Booked: <span> {{Hotel_Room_Application_Record.timestamp}} </span></h1>
            </div>
        </a>
        {% endfor %}
    </main>
</body>
</html>

home/templates/home/details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <header>
        <center>
            <h1>XYZ HOTEL</h1>
            <div>
                <a href="{% url 'home:recordview' %}"><button>Go back to records</button></a>
                <a href="{% url 'accounts:logoutview' %}"><button>Log Out</button></a>
            </div>
        </center>
    </header>
    <main>
        <center><h2>Record <span> {{posts.id}}</span></h2></center>
            <div>
                <h1>Name: <span> {{ posts.Occupant_Name }} </span></h1>
                <h1>Room Number: <span> {{posts.Room_number}} </span></h1>
                <h1>Email: <span> {{ posts.Occupant_email }} </span></h1>
                <h1>Occupation: <span> {{posts.Occupant_occupation }} </span></h1>
                <h1>Number of night: <span> {{ posts.Number_of_night }} </span></h1>
                <h1>Start date<span> {{ posts.Start_date }} </span></h1>
                <h1>End date: <span> {{ posts.End_date }} </span></h1>
                <h1>Registered by <span> {{posts.Registered_by}} </span>on <span> {{posts.timestamp}} </span></h1>
                <h1>Amount paid: #<span> {{posts.Amount_paid_in_Naira}} </span></h1>
            </div>
    </main>   
</body>
</html>

home/templates/home/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <header>
        <center><h1>XYZ HOTEL</h1></center>
    </header>
    <main>
        <center><h1>Welcome to XYZ Hotel</h1></center> 
        <center>
            <a href="{% url 'accounts:signupview' %}"><button>Sign up as admin</button></a>
            <p>Already have an account? <span><a href="{% url 'accounts:signinview' %}"> Sign In</a></span></p>
        </center>
    </main>
    <footer>

    </footer>
</body>
</html>